lintとテストのジョブの設定を修正

diff --git a/.github/workflows/lint-and-test.yml b/.github/workflows/lint-and-test.yml
--- a/.github/workflows/lint-and-test.yml
+++ b/.github/workflows/lint-and-test.yml
@@ -1,6 +1,6 @@
-name: Build
+name: Lint and test
 
-on: [push]
+on: push
 
 jobs:
   zeitwerk:
@@ -15,12 +15,11 @@ jobs:
           bundler-cache: true
       - run: bin/rails zeitwerk:check
 
-  sorbet-update:
-    name: Update Sorbet types
+  sorbet:
+    name: Sorbet
     permissions:
       contents: write
     runs-on: ubuntu-latest
-    if: ${{ github.actor == 'dependabot[bot]' }}
     steps:
       - uses: actions/checkout@v4
       - name: Setup Ruby and install gems
@@ -29,26 +28,20 @@ jobs:
           ruby-version: 3.2.2
           bundler-cache: true
       - run: bin/rails sorbet:update
-      - name: Commit & push
+      - name: Push RBI files or fail
         run: |
-          git config user.email 49699333+dependabot[bot]@users.noreply.github.com
-          git config user.name dependabot[bot]
-          git add .
-          git commit -m "Update types"
-          git push
-
-  sorbet:
-    name: Sorbet
-    if: ${{ always() }} # `sorbet-update` が実行されないときも実行する
-    needs: sorbet-update
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: Setup Ruby and install gems
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: 3.2.2
-          bundler-cache: true
+          if [ -n "$(git status --porcelain)" ]; then
+            if [ "$GITHUB_ACTOR" = "dependabot[bot]" ]; then
+              git config user.email 49699333+dependabot[bot]@users.noreply.github.com
+              git config user.name dependabot[bot]
+              git add .
+              git commit -m "Update RBI files"
+              git push
+            else
+              echo "Error! 未更新のRBIファイルがあるようです。bin/rails sorbet:update を実行して差分をコミットしてください。"
+              exit 1
+            fi
+          fi
       - run: bin/srb tc
 
   standard:
